server:
  port: 8090
  tomcat:
    uri-encoding: UTF-8
    servlet:
      context-path: /yyblog/

spring:
  profiles:
    active: @profileActive@

  datasource:
    url: jdbc:mysql://localhost/blog?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode:
    servlet:
      content-type: text/html
    cache: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
